# Generated by Django 5.2.16 on 2026-07-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_usageevent_processing_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyusage',
            options={'ordering': ('-date',), 'verbose_name': 'uso diario', 'verbose_name_plural': 'usos diarios'},
        ),
        migrations.AlterModelOptions(
            name='interactionreservation',
            options={'verbose_name': 'reserva de interacción', 'verbose_name_plural': 'reservas de interacción'},
        ),
        migrations.AlterModelOptions(
            name='usageevent',
            options={'ordering': ('-created_at',), 'verbose_name': 'evento de consumo', 'verbose_name_plural': 'eventos de consumo'},
        ),
    ]
