# Generated by Django 5.2.16 on 2026-07-31 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0003_alter_dailyusage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyusage',
            name='date',
            field=models.DateField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='dailyusage',
            name='interaction_count',
            field=models.PositiveIntegerField(default=0, verbose_name='interacciones'),
        ),
        migrations.AlterField(
            model_name='dailyusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='action',
            field=models.CharField(max_length=80, verbose_name='acción'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completado el'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='error_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código de error'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='interaction_cost',
            field=models.PositiveIntegerField(default=1, verbose_name='coste de interacción'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadatos'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='processing_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='tiempo de proceso (ms)'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID de solicitud'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='status',
            field=models.CharField(choices=[('authorized', 'Authorized'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected_quota', 'Rejected by quota'), ('rejected_auth', 'Rejected by authentication'), ('cancelled', 'Cancelled')], max_length=30, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validado el'),
        ),
    ]
