# Generated by Django 5.2.16 on 2026-07-31 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_clientapplication_base_url_and_more'),
        ('usage', '0004_alter_dailyusage_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usages', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='interactionreservation',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.clientapplication', verbose_name='aplicación'),
        ),
        migrations.AlterField(
            model_name='interactionreservation',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='usage.usageevent', verbose_name='evento'),
        ),
        migrations.AlterField(
            model_name='interactionreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='applications.clientapplication', verbose_name='aplicación'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
