# Generated by Django 5.2.16 on 2026-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0005_alter_dailyusage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='status',
            field=models.CharField(choices=[('authorized', 'Autorizado'), ('processing', 'En proceso'), ('completed', 'Completado'), ('failed', 'Fallido'), ('rejected_quota', 'Rechazado por cuota'), ('rejected_auth', 'Rechazado por autenticación'), ('cancelled', 'Cancelado')], max_length=30, verbose_name='estado'),
        ),
    ]
