# Generated by Django 5.2.16 on 2026-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0006_alter_usageevent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionreservation',
            name='request_id',
            field=models.UUIDField(unique=True, verbose_name='ID de solicitud'),
        ),
    ]
