# Generated by Django 5.2.16 on 2026-07-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',), 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
