# Generated by Django 5.2.16 on 2026-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='términos aceptados el'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='correo verificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='bloqueado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
    ]
