# Generated by Django 5.2.16 on 2026-07-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('daily_interaction_limit', 'code'), 'verbose_name': 'plan', 'verbose_name_plural': 'planes'},
        ),
        migrations.AlterModelOptions(
            name='planchangelog',
            options={'ordering': ('-created_at',), 'verbose_name': 'historial de cambio de plan', 'verbose_name_plural': 'historial de cambios de plan'},
        ),
        migrations.AlterModelOptions(
            name='userplan',
            options={'verbose_name': 'asignación de plan', 'verbose_name_plural': 'asignaciones de planes'},
        ),
    ]
