# Generated by Django 5.2.16 on 2026-07-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plan_options_alter_planchangelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='daily_interaction_limit',
            field=models.PositiveIntegerField(verbose_name='límite diario de interacciones'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='planchangelog',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='motivo'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='asignado el'),
        ),
    ]
