# Generated by Django 5.2.16 on 2026-07-31 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_code_alter_plan_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planchangelog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='cambiado por'),
        ),
        migrations.AlterField(
            model_name='planchangelog',
            name='new_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_logs', to='plans.plan', verbose_name='plan nuevo'),
        ),
        migrations.AlterField(
            model_name='planchangelog',
            name='previous_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_logs', to='plans.plan', verbose_name='plan anterior'),
        ),
        migrations.AlterField(
            model_name='planchangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_changes', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plans', to=settings.AUTH_USER_MODEL, verbose_name='asignado por'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='plans.plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
