# Generated by Django 5.2.16 on 2026-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_planchangelog_changed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planchangelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
    ]
