# Generated by Django 5.2.16 on 2026-07-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientapplication',
            options={'ordering': ('name',), 'verbose_name': 'aplicación cliente', 'verbose_name_plural': 'aplicaciones cliente'},
        ),
    ]
