# Generated by Django 5.2.16 on 2026-07-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_clientapplication_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapplication',
            name='base_url',
            field=models.URLField(verbose_name='URL base'),
        ),
        migrations.AlterField(
            model_name='clientapplication',
            name='consumes_quota',
            field=models.BooleanField(default=True, verbose_name='consume cuota'),
        ),
        migrations.AlterField(
            model_name='clientapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada el'),
        ),
        migrations.AlterField(
            model_name='clientapplication',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='clientapplication',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='clientapplication',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='identificador'),
        ),
    ]
